spring.application.name=ProjektKodSWI

spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/XEPDB1
spring.datasource.username=system
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true